id: PE3FBEFEF
initial_creation_type: input
source_metadata:
  Title: Balimālikā
  Editor: Sumatisimha
  Publisher: '-'
  Place of Publication: Japan
  Year: '1967'
  बलिमालिका:
    Text Version: Devanagari
    Input Personnel: Miroj Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:10:22.292380'
last_modified_at: '2022-03-08T17:10:22.292389'
